services:
  proxy:
    build: ./proxy # proxy? omaigat
    restart: unless-stopped
    ports:
      - 8115:8115
  backend:
    build: ./web
    restart: unless-stopped
    environment:
      - FLAG=CTFITB2025{wazeazureğŸ˜­ğŸ˜­ğŸ˜­_plissssğŸ˜­ğŸ˜­ğŸ˜­_jangan_pensi_ctf_duluğŸ˜­ğŸ˜­ğŸ˜­_HUAAAAAAAAAAAAğŸ˜­ğŸ˜­ğŸ˜­}